name: Pull Request Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PR Review Script
        env:
          ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python pr_reviewer_2.py --repo ${{ github.repository }} --pr ${{ github.event.pull_request.number }}
